export default {
	"en":{
				"Amount":"Amount:",
				"Reciever":"Reciever:",
				"Copy":"Copy",
				"WalletAddress":"Wallet Address",
				"Privatekey":"Private key",
				"Balance":"Balance",
				"Send":"Send",
				"confirmation":"Waiting 2~3 minutes for confirmation.",
				"ReferrerID":"Referrer ID",
				"ContractAddress":"Contract Address",
				"Power":"Power",
				"TotalPower":"Total Power",
				"ID":"ID",
				"InvitationCode":"Invitation Code",
				"AffiliateLink":"Affiliate Link",
				"AndroidAPP":"Android APP",
				"IosAPP":"Ios APP",
				"CoinReceived":"Coin Received",
				"PowerReceived":"Power Received",
				"register":"register",
				"matrix":"matrix",
				"Token":"Token",
				"Copied":"Copied",
				"Cleard":"Cleard",
				"Clearprivate":"Clear private key will lost your wallet, please copy and store it first. Do you confirm to clear?",
				"correctaddress.":"Please use correct address.",
				"incorrect":"Frig Amount is incorrect.",
				"Send2":"Send...",
				"friginsufficientlease":"insufficient balance to do, at lease *** Frig.",
				"frigsendingto":"You are sending to *** Frig to ***, continue?",
				"SendFailed":"Send Failed",
				"SendSucceed":"Send Succeed.",
				"odininsufficientlease":"insufficient balance to do, at lease *** ODIN.",
				"odinsendingto":"You are sending to *** ODIN to ***, continue?",
				"toregister":"insufficient balance to register, at lease *** ODIN",
				"Registercost":"Register will cost *** ODIN, continue?",
				"RegisterFailed":"Register Failed.",
				"RegisterSucceed":"Register Succeed.",
				"Upgrade":"Upgrade to level *** ...",
				"UpgradeSucceed":"Upgrade Succeed.",
				"UpgradeFailed":"Upgrade Failed.",
				"Upgradelease":"Upgrade to level ***, at lease *** ODIN.",
				"Upgradecost":"Upgrade to level *** will cost *** ODIN, continue?",
				"CreateWallet":"Create a Wallet",
				"ImportWallet":"Import a Wallet",
				"DownloadAndroid":"Download Android App",
				"DownloadIos":"Download Ios App",
				// "DownloadAndroid_kr":"Android 앱 다운로드",
				// "DownloadIos_kr":"Ios 앱 다운로드",
				// "DownloadAndroid_su":"Скачать приложение для Android",
				// "DownloadIos_su":"Скачать приложение для iOS",
				"Import":"Import",
				"IDincorrect":"ID is incorrect.",
				"Privateincorrect":"Private key is incorrect.",
				"Confirming":"Confirming",
				"Clear":"Clear",
				"Amountincorrect":"Amount is incorrect."
			},
	"korea":{
				"Amount":"Количество:",
				"Reciever":"양:",
				"Copy":"부",
				"WalletAddress":"지갑 주소",
				"Privatekey":"개인 키",
				"Balance":"밸런스",
				"Send":"보내다",
				"confirmation":"확인을 위해 2 ~ 3 분 대기.",
				"ReferrerID":"추천인 ID",
				"ContractAddress":"계약 주소",
				"Power":"힘",
				"TotalPower":"총 전력",
				"ID":"ID",
				"InvitationCode":"초대 코드",
				"AffiliateLink":"제휴 링크",
				"AndroidAPP":"안드로이드 앱",
				"IosAPP":"Ios 앱",
				"CoinReceived":"코인 수령",
				"PowerReceived":"받은 전력",
				"register":"레지스터",
				"matrix":"매트릭스",
				"Token":"토큰",
				"Copied":"복사 됨",
				"Cleard":"클리어",
				"Clearprivate":"명확한 개인 키는 지갑을 잃어 버릴 수 있으므로 먼저 복사하여 저장하십시오. 삭제 하시겠습니까?",
				"correctaddress.":"정확한 주소를 사용하십시오.",
				"incorrect":"Frig 금액이 잘못되었습니다.",
				"Send2":"보내다...",
				"friginsufficientlease":"할 수있는 불충분 한 균형, 적어도 *** Frig.",
				"frigsendingto":"*** Frig to ***에 보내는 중입니다. 계속 하시겠습니까?",
				"SendFailed":"보내기 실패",
				"SendSucceed":"성공을 보냅니다.",
				"odininsufficientlease":"할 수있는 불충분 한 균형 *** ODIN.",
				"odinsendingto":"*** ODIN (으)로 ***에 보내는 중입니다. 계속 하시겠습니까?",
				"toregister":"등록하기에 불충분 한 잔액, 임대 *** ODIN",
				"Registercost":"등록 비용 *** ODIN, 계속 하시겠습니까?",
				"RegisterFailed":"등록 실패.",
				"RegisterSucceed":"등록 성공.",
				"Upgrade":"레벨로 업그레이드 *** ...",
				"UpgradeSucceed":"업그레이드 성공.",
				"UpgradeFailed":"업그레이드에 실패했습니다.",
				"Upgradelease":"레벨 ***로 업그레이드, 임대 *** ODIN.",
				"Upgradecost":"*** 레벨로 업그레이드하면 *** ODIN 비용이 발생합니다. 계속 하시겠습니까?",
				"CreateWallet":"지갑 생성",
				"ImportWallet":"지갑 가져 오기",
				// "DownloadAndroid":"Download Android App",
				// "DownloadIos":"Download Ios App",
				"DownloadAndroid":"Android 앱 다운로드",
				"DownloadIos":"Ios 앱 다운로드",
				// "DownloadAndroid_su":"Скачать приложение для Android",
				// "DownloadIos_su":"Скачать приложение для iOS",
				"Import":"수입",
				"IDincorrect":"ID가 올바르지 않습니다.",
				"Privateincorrect":"개인 키가 올바르지 않습니다.",
				"Confirming":"확인",
				"Clear":"맑은",
				"Amountincorrect":"금액이 잘못되었습니다."
	},
	"russia":{
				"Amount":"Приемник:",
				"Reciever":"리시버:",
				"Copy":"Копировать",
				"WalletAddress":"Адрес кошелька",
				"Privatekey":"Закрытый ключ",
				"Balance":"Остаток средств",
				"Send":"послать",
				"confirmation":"Ожидание 2–3 минут подтверждения.",
				"ReferrerID":"ID реферера",
				"ContractAddress":"Адрес контракта",
				"Power":"Сила",
				"TotalPower":"Суммарная мощность",
				"ID":"ID",
				"InvitationCode":"Код приглашения",
				"AffiliateLink":"Партнерская ссылка",
				"AndroidAPP":"Приложение для Android",
				"IosAPP":"Приложение для iOS",
				"CoinReceived":"Монета получена",
				"PowerReceived":"Полученная мощность",
				"register":"регистр",
				"matrix":"матрица",
				"Token":"Токен",
				"Copied":"Скопировано",
				"Cleard":"Клирд",
				"Clearprivate":"Очистить закрытый ключ приведет к потере вашего кошелька, пожалуйста, сначала скопируйте и сохраните его. Вы подтверждаете, чтобы очистить?",
				"correctaddress.":"Пожалуйста, используйте правильный адрес.",
				"incorrect":"Сумма Frig неверна.",
				"Send2":"Послать...",
				"friginsufficientlease":"недостаточный баланс для выполнения, при аренде *** Frig.",
				"frigsendingto":"Вы отправляете *** Frig на ***, продолжить?",
				"SendFailed":"Отправить не удалось",
				"SendSucceed":"Отправить Успешно.",
				"odininsufficientlease":"недостаточный баланс делать, при аренде *** ODIN.",
				"odinsendingto":"Вы отправляете *** ODIN на ***, продолжить?",
				"toregister":"недостаточный баланс для регистрации, при аренде *** ODIN",
				"Registercost":"Регистрация будет стоить *** ODIN, продолжить?",
				"RegisterFailed":"Регистрация не удалась.",
				"RegisterSucceed":"Зарегистрироваться Успешно.",
				"Upgrade":"Повышение до уровня *** ...",
				"UpgradeSucceed":"Успешное обновление.",
				"UpgradeFailed":"Ошибка обновления.",
				"Upgradelease":"Повышение до уровня ***, в аренду *** ODIN.",
				"Upgradecost":"Повышение до уровня *** будет стоить *** ODIN, продолжить?",
				"CreateWallet":"Создать кошелек",
				"ImportWallet":"Импортировать кошелек",
				// "DownloadAndroid":"Download Android App",
				// "DownloadIos":"Download Ios App",
				// "DownloadAndroid_kr":"Android 앱 다운로드",
				// "DownloadIos_kr":"Ios 앱 다운로드",
				"DownloadAndroid":"Скачать приложение для Android",
				"DownloadIos":"Скачать приложение для iOS",
				"Import":"Импортировать",
				"IDincorrect":"ID неверный.",
				"Privateincorrect":"Приватный ключ неверен.",
				"Confirming":"Подтверждая",
				"Clear":"Чисто",
				"Amountincorrect":"Сумма неверна."
	}
}
